name: prwt-remote
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Summarize login session times or check login session for a timestamp. # 79 char long summary
description: |
  Script sums the login session times on a remote linux host. It prints the start/end
  dates for each week of the year for which there is login session data.
  Optionally the script prints the summary for one week using the week number.
  
  The script can check if a timestamp is present in the login session data.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  prwt-remote:
    command: bin/20a90d3114acdc96_prwt-remote.py

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil

